version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - algaworks_esr:/var/lib/mysql

volumes:
  algaworks_esr: